### ISSUE TITLE
库中是否缺少了数据 ROI 区域的 CSV文件？

### ISSUE THREAD

**Issue by MomoiaMoia** [Zhou-Hangyu/allclear#2]
您好！您工作提出的数据集看起来非常丰富和完善！在尝试下载数据集时，我遇到了缺少文件的问题。

具体来说，在 `dataset/landsat8/download_data_landsat8_train1.sh` 文件的第 31 行中提到了一个 CSV 文件，例如：
`ROIS_PATH="/share/hariharan/cloud_removal/allclear/experimental_scripts/data_prep/v3_distribution_train_20Ksamples.csv"`

然而我在库中没有找到这些对应的 CSV 文件。请问未来会有计划上传这些文件吗？

期待您的回复！

**Comment by Zhou-Hangyu** [comment]
Thank you! Yes, we are cleaning up our codebase and uploading our dataset to a publicly accessible server. Thanks for pointing out this issue. We will resolve it in the coming days. Stay tuned!

**Comment by MomoiaMoia** [comment]
> Thank you! Yes, we are cleaning up our codebase and uploading our dataset to a publicly accessible server. Thanks for pointing out this issue. We will resolve it in the coming days. Stay tuned!

Thanks!
